"""specie_name_unique

Revision ID: 6aa985a4da35
Revises: ebc1c1c25812
Create Date: 2023-12-02 21:00:42.558934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa985a4da35'
down_revision: Union[str, None] = 'ebc1c1c25812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'species', ['specie_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='unique')
    # ### end Alembic commands ###
